steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/discord-bot/discord-bot:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/discord-bot/discord-bot:latest",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/discord-bot/discord-bot:latest"
serviceAccount: "$PROJECT_ID@cloudbuild.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY