FROM node:19

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . .

# Start the application
CMD [ "npm", "run", "dev" ]