version: '3.8'

services:
  backend:
    image: us-central1-docker.pkg.dev/tamu-esports-infrastructure/backend/backend:latest
    container_name: backend
    env_file: .env
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

  discord_bot:
    image: us-central1-docker.pkg.dev/tamu-esports-infrastructure/discord-bot/discord-bot:latest
    container_name: discord_bot
    env_file: .env
    networks:
      - app-network
    depends_on:
      - backend
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
