version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    env_file: .env.production
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./.env.production:/app/.env
    networks:
      - app-network
    restart: unless-stopped

  discord_bot:
    build:
      context: ./discord_bot
      dockerfile: Dockerfile.prod
    container_name: discord_bot
    env_file: .env.production
    volumes:
      - ./discord_bot:/app
      - ./.env.production:/app/.env
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped