version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file: .env.development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./.env.development:/app/.env
    networks:
      - app-network

  discord_bot:
    build:
      context: ./discord_bot
      dockerfile: Dockerfile.dev
    container_name: discord_bot
    env_file: .env.development
    volumes:
      - ./discord_bot:/app
      - ./.env.development:/app/.env
    networks:
      - app-network
    depends_on:
      - backend