steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest",
        "-f",
        "./backend/Dockerfile.prod",
        "./backend",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest"
