steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest",
        ".",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest"
serviceAccount: "376083662673@cloudbuild.gserviceaccount.com"
logsBucket: gs://tamu-esports-infrastructure-build-logs-bucket