FROM node:19

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . .

# Expose the necessary port and start the application
EXPOSE 3001
CMD [ "npm", "run", "start:dev" ]
